#S3 / MinIO
spark.hadoop.fs.s3a.endpoint        abc
spark.hadoop.fs.s3a.access.key      abc
spark.hadoop.fs.s3a.secret.key      abc
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl            abc
spark.hadoop.fs.s3a.aws.credentials.provider    abc

#Delta Lake
spark.sql.extensions                abc
spark.sql.catalog.spark_catalog     abc

#Hive Metastore
spark.sql.catalogImplementation     abc
spark.hadoop.hive.metastore.uris    abc

#Performance
spark.executor.memory               2g
spark.driver.memory                 2g